---
- name: Provisionar Instância EC2 para Master Ansible
  hosts: localhost
  gather_facts: no
  collections:
    - amazon.aws
  vars:
    ec2_key_name: "master-ansible-key"
    ec2_instance_type: "t2.micro"
    ec2_image: "ami-04b70fa74e45c3917"  # Substituir pelo ID da AMI Linux desejada
    ec2_volume_size: 10
    region: "us-east-1"
    security_group_name: "master-ansible-sg"
    user_data_template: |
      #!/bin/bash
      echo "Atualizando e instalando dependências..."
      sudo apt-get update -y
      sudo apt-get upgrade -y
      sudo apt-get install -y git vim unzip ansible-core python3 python3-pip

      echo "Instalando boto3 e botocore..."
      sudo apt-get install -y python3-boto3 python3-botocore

      echo "Instalando AWS CLI..."
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install

      echo "Instalando coleções Ansible Galaxy..."
      ansible-galaxy collection install amazon.aws
      ansible-galaxy collection install community.aws

      echo "Clonando repositório do GitHub..."
      sudo -u ubuntu git clone https://github.com/giovanni-gava/iac-mack.git /home/ubuntu/iac-mack

      echo "Configurando credenciais da AWS..."
      sudo mkdir -p /home/ubuntu/.aws
      cat <<EOF | sudo tee /home/ubuntu/.aws/credentials
      [default]
      AWS_ACCESS_KEY_ID=x
      AWS_SECRET_ACCESS_KEY=x
      AWS_DEFAULT_REGION=x
      EOF
      sudo chown ubuntu:ubuntu /home/ubuntu/.aws/credentials
      sudo chmod 600 /home/ubuntu/.aws/credentials

      echo "Configuração concluída com sucesso!"
  tasks:
    - name: Carregar variáveis de ambiente do .bashrc
      shell: . ~/.bashrc && env
      register: shell_output

    - name: Exibir conteúdo do shell_output
      debug:
        var: shell_output.stdout_lines

    - name: Setar variáveis de ambiente
      set_fact:
        vpc_id: "{{ lookup('env', 'VPC_ID') }}"
        subnet_id_az1: "{{ lookup('env', 'SUBNET_ID_AZ1') }}"
        subnet_id_az2: "{{ lookup('env', 'SUBNET_ID_AZ2') }}"
        region: "{{ lookup('ini', 'AWS_DEFAULT_REGION section=default file=~/.aws/credentials') }}"

    - name: Exibir variáveis carregadas
      debug:
        msg: "VPC_ID: {{ vpc_id }}, SUBNET_ID_AZ1: {{ subnet_id_az1 }}, SUBNET_ID_AZ2: {{ subnet_id_az2 }}, REGION: {{ region }}"

    - name: Criar par de chaves
      amazon.aws.ec2_key:
        name: "{{ ec2_key_name }}"
        region: "{{ region }}"
        state: present
      register: ec2_key

    - name: Salvar chave privada no diretório home do usuário executante
      copy:
        content: "{{ ec2_key.key.private_key }}"
        dest: "{{ lookup('env', 'HOME') }}/{{ ec2_key_name }}.pem"
        mode: '0600'
      when: ec2_key.key.private_key is defined

    - name: Criar grupo de segurança
      amazon.aws.ec2_group:
        name: "{{ security_group_name }}"
        description: Security group for webserver
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports:
              - 80
            cidr_ip: 0.0.0.0/0
        state: present
        region: "{{ region }}"
      register: sg

    - name: Lançar instância EC2
      amazon.aws.ec2_instance:
        name: "webserver"
        key_name: "{{ ec2_key_name }}"
        instance_type: "{{ ec2_instance_type }}"
        image_id: "{{ ec2_image }}"
        vpc_subnet_id: "{{ subnet_id_az1 }}"
        security_group: "{{ sg.group_id }}"
        wait: yes
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: "{{ ec2_volume_size }}"
        network:
          assign_public_ip: yes
        user_data: "{{ user_data_template }}"
        region: "{{ region }}"
      register: ec2

    - name: Depurar detalhes da instância EC2
      debug:
        var: ec2

    - name: Remover variável EC2_INSTANCE_ID existente do .bashrc
      lineinfile:
        path: ~/.bashrc
        state: absent
        regexp: '^export EC2_INSTANCE_ID='

    - name: Exportar Instance ID para .bashrc
      lineinfile:
        path: ~/.bashrc
        line: "export EC2_INSTANCE_ID={{ ec2.instances[0].instance_id }}"
        create: yes

    - name: Carregar novas variáveis de ambiente do .bashrc
      shell: . ~/.bashrc && env
      register: new_shell_output

    - name: Confirmar se o novo Instance ID foi exportado corretamente
      debug:
        msg: "Novo EC2_INSTANCE_ID: {{ new_shell_output.stdout_lines | select('search', '^EC2_INSTANCE_ID=') | list | first | split('=') | last }}"

    - name: Verificar se o novo EC2_INSTANCE_ID foi atualizado
      assert:
        that: "lookup('env', 'EC2_INSTANCE_ID') == ec2.instances[0].instance_id"
        fail_msg: "O EC2_INSTANCE_ID não foi atualizado corretamente."
        success_msg: "O EC2_INSTANCE_ID foi atualizado corretamente."

    - name: Variáveis de ambiente carregadas com sucesso!
      debug:
        msg: "EC2_INSTANCE_ID: {{ lookup('env', 'EC2_INSTANCE_ID') }}"


