---
- name: Criar RDS na AWS
  hosts: localhost
  gather_facts: no
  collections:
    - amazon.aws
  vars_files:
    - vars/vpc_vars.yml
    - vars/ec2_vars.yml
  tasks:
    - name: Exibir variáveis carregadas de vpc_vars.yml
      debug:
        msg: "VPC_ID: {{ vpc_id }}, SUBNET_ID_AZ1: {{ subnet_id_az1 }}, SUBNET_ID_AZ2: {{ subnet_id_az2 }}"

    - name: Exibir variáveis carregadas de ec2_vars.yml
      debug:
        msg: "SG_ID: {{ sg_id }}"

    - name: Setar região
      set_fact:
        region: "{{ lookup('ini', 'AWS_DEFAULT_REGION section=default file=~/.aws/credentials') }}"

    - name: Verificar se as variáveis estão setadas corretamente
      debug:
        msg: "VPC_ID: {{ vpc_id }}, SUBNET_ID_AZ1: {{ subnet_id_az1 }}, SUBNET_ID_AZ2: {{ subnet_id_az2 }}, SG_ID: {{ sg_id }}, REGION: {{ region }}"

    - name: Criar grupo de segurança para RDS
      amazon.aws.ec2_group:
        name: "rds-security-group"
        description: "Security group for RDS instance"
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            ports:
              - 3306
            cidr_ip: 0.0.0.0/0
        region: "{{ region }}"
        state: present
      register: rds_sg

    - name: Adicionar regra de entrada para SG_ID no grupo de segurança do RDS
      amazon.aws.ec2_group:
        name: "{{ rds_sg.group_name }}"
        description: "Allow access from SG_ID"
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            ports:
              - 3306
            group_id: "{{ sg_id }}"
        region: "{{ region }}"
        state: present

    - name: Criar DB Subnet Group
      amazon.aws.rds_subnet_group:
        name: "my-subnet-group"
        description: "Subnet group for RDS instances"
        subnets:
          - "{{ subnet_id_az1 }}"
          - "{{ subnet_id_az2 }}"
        region: "{{ region }}"
        state: present
      register: db_subnet_group

    - name: Criar RDS instance
      amazon.aws.rds_instance:
        db_instance_identifier: "webserver-db"
        db_name: "webserverdb"
        allocated_storage: 20
        db_instance_class: db.t3.micro
        engine: mysql
        master_username: "admin"
        master_user_password: "password"
        vpc_security_group_ids:
          - "{{ rds_sg.group_id }}"
        db_subnet_group_name: "{{ db_subnet_group.name }}"
        multi_az: no
        region: "{{ region }}"
        state: present
        tags:
          Name: "webserver-db"
      register: rds

    - name: Exibir detalhes da RDS criada
      debug:
        var: rds

    - name: Exportar variáveis criadas para rds_vars.yml
      copy:
        content: |
          rds_security_group_id: "{{ rds_sg.group_id }}"
          rds_subnet_group_name: "{{ db_subnet_group.name }}"
          rds_endpoint: "{{ rds.endpoint }}"
        dest: "vars/rds_vars.yml"
