---
- name: Criar VPC e Subnet na AWS
  hosts: localhost
  gather_facts: no
  vars:
    region: us-east-1
    vpc_cidr: "10.0.0.0/16"
    subnet_cidr: "10.0.1.0/24"
  tasks:
    - name: Criar VPC
      amazon.aws.ec2_vpc_net:
        name: minha_vpc
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ region }}"
        state: present
      register: vpc

    - name: VPC criada com sucesso!
      debug:
        var: vpc

    - name: Criar Subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ subnet_cidr }}"
        region: "{{ region }}"
        state: present
        map_public: yes
      register: subnet

    - name: Subnet criada com sucesso!
      debug:
        var: subnet

    - name: Criar Internet Gateway
      amazon.aws.ec2_vpc_igw:
        state: present
      register: igw

    - name: Verificar criação do Internet Gateway
      debug:
        var: igw

    - name: Anexar Internet Gateway à VPC
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        internet_gateway_id: "{{ igw.gateway_id }}"
        state: present
      when: igw.gateway_id is defined

    - name: Criar tabela de roteamento
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        state: present
      register: route_table

    - name: Adicionar rota para o Internet Gateway
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        route_table_id: "{{ route_table.route_table.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
        state: present

    - name: Adicionar rota local à tabela de roteamento
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        route_table_id: "{{ route_table.route_table.id }}"
        routes:
          - dest: "{{ vpc_cidr }}"
            local_target: true
        state: present

    - name: Associar tabela de roteamento à Subnet
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        route_table_id: "{{ route_table.route_table.id }}"
        subnets:
          - "{{ subnet.subnet.id }}"
        state: present

    - name: Remover VPC_ID existente do .bashrc
      lineinfile:
        path: ~/.bashrc
        state: absent
        regexp: '^export VPC_ID='

    - name: Exportar VPC ID para .bashrc
      lineinfile:
        path: ~/.bashrc
        line: "export VPC_ID={{ vpc.vpc.id }}"
        create: yes

    - name: VPC ID exportado com sucesso!
      debug:
        msg: "VPC ID exportado com sucesso para .bashrc!"

    - name: Remover SUBNET_ID existente do .bashrc
      lineinfile:
        path: ~/.bashrc
        state: absent
        regexp: '^export SUBNET_ID='

    - name: Exportar Subnet ID para .bashrc
      lineinfile:
        path: ~/.bashrc
        line: "export SUBNET_ID={{ subnet.subnet.id }}"
        create: yes

    - name: Subnet ID exportado com sucesso!
      debug:
   
