---
- name: Provisionar Instância EC2
  hosts: localhost
  gather_facts: no
  collections:
    - amazon.aws
  vars_files:
    - vpc_vars.yml
  vars:
    ec2_instance_type: "t2.micro"
    ec2_image: "ami-04b70fa74e45c3917"  # Substituir pelo ID da AMI Linux desejada
    ec2_volume_size: 10
    security_group_name: "webserver-sg"
    ec2_key_name: "webserver-key"
    user_data_template: |
      #!/bin/bash
      sudo apt update -y
      sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      sudo apt update -y
      sudo apt install -y docker-ce
      sudo systemctl start docker
      sudo systemctl enable docker
      sudo docker run -d -p 80:80 --name nginx nginx
      # Garantir que o SSH esteja rodando
      sudo apt install -y openssh-server
      sudo systemctl enable ssh
      sudo systemctl start ssh
      # Verificar se o Docker está em execução
      sudo systemctl status docker
      # Verificar se o container Nginx está em execução
      sudo docker ps -a

  tasks:
    - name: Exibir variáveis carregadas
      debug:
        msg: "VPC_ID: {{ vpc_id }}, SUBNET_ID_AZ1: {{ subnet_id_az1 }}, SUBNET_ID_AZ2: {{ subnet_id_az2 }}, REGION: {{ region }}"

    - name: Criar par de chaves
      amazon.aws.ec2_key:
        name: "{{ ec2_key_name }}"
        region: "{{ region }}"
        state: present
      register: ec2_key

    - name: Salvar chave privada no diretório home do usuário executante
      copy:
        content: "{{ ec2_key.key.private_key }}"
        dest: "{{ lookup('env', 'HOME') }}/{{ ec2_key_name }}.pem"
        mode: '0600'
      when: ec2_key.key.private_key is defined

    - name: Criar grupo de segurança
      amazon.aws.ec2_group:
        name: "{{ security_group_name }}"
        description: Security group for webserver
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports:
              - 80
            cidr_ip: 0.0.0.0/0
        state: present
        region: "{{ region }}"
      register: sg

    - name: Lançar instância EC2
      amazon.aws.ec2_instance:
        name: "webserver"
        key_name: "{{ ec2_key_name }}"
        instance_type: "{{ ec2_instance_type }}"
        image_id: "{{ ec2_image }}"
        vpc_subnet_id: "{{ subnet_id_az1 }}"
        security_group: "{{ sg.group_id }}"
        wait: yes
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: "{{ ec2_volume_size }}"
        network:
          assign_public_ip: yes
        user_data: "{{ user_data_template }}"
        region: "{{ region }}"
      register: ec2

    - name: Aguardar a inicialização da instância EC2
      wait_for:
        host: "{{ ec2.instances[0].public_ip_address }}"
        port: 22
        state: started
        timeout: 300

    - name: Depurar detalhes da instância EC2
      debug:
        var: ec2

    - name: Exportar variáveis para o arquivo de variáveis do Ansible
      copy:
        content: |
          ec2_instance_id: "{{ ec2.instances[0].instance_id }}"
          ec2_key_name: "{{ ec2_key_name }}"
          sg_id: "{{ sg.group_id }}"
        dest: "{{ playbook_dir }}/ec2_vars.yml"

    - name: Variáveis de ambiente carregadas com sucesso!
      debug:
        msg: "EC2_INSTANCE_ID: {{ ec2.instances[0].instance_id }}, EC2_KEY_NAME: {{ ec2_key_name }}, SG_ID: {{ sg.group_id }}"
