---
- name: Provisionar Instância EC2 para Master Ansible
  hosts: localhost
  gather_facts: no
  collections:
    - amazon.aws
  vars:
    ec2_key_name: "master-ansible-key"
    ec2_instance_type: "t2.micro"
    ec2_image: "ami-04b70fa74e45c3917"  # Substituir pelo ID da AMI Linux desejada
    ec2_volume_size: 10
    region: "us-east-1"
    user_data_template: |
      #!/bin/bash
      sudo dnf update -y
      sudo dnf install -y ansible python3 python3-pip git vim openssh-server
      sudo pip3 install boto3 botocore
      sudo ansible-galaxy collection install amazon.aws
      sudo ansible-galaxy collection install community.aws
      sudo systemctl enable sshd
      sudo systemctl start sshd
      sudo -u ec2-user git clone https://github.com/giovanni-gava/iac-mack.git /home/ec2-user/iac-mack
      sudo -u ec2-user mkdir -p /home/ec2-user/.aws
      sudo -u ec2-user touch /home/ec2-user/.aws/credentials
      sudo -u ec2-user chmod 600 /home/ec2-user/.aws/credentials
      cat <<EOF | sudo tee /home/ec2-user/.aws/credentials
      [default]
      aws_access_key_id=
      aws_secret_access_key=
      AWS_DEFAULT_REGION=us-east-1
      EOF
  tasks:
    - name: Criar par de chaves
      amazon.aws.ec2_key:
        name: "{{ ec2_key_name }}"
        region: "{{ region }}"
        state: present
      register: ec2_key

    - name: Salvar chave privada no diretório home do usuário executante
      copy:
        content: "{{ ec2_key.key.private_key }}"
        dest: "{{ lookup('env', 'HOME') }}/{{ ec2_key_name }}.pem"
        mode: '0600'
      when: ec2_key.key.private_key is defined

    - name: Remover variável EC2_KEY_NAME existente do .bashrc
      lineinfile:
        path: ~/.bashrc
        state: absent
        regexp: '^export EC2_KEY_NAME='

    - name: Exportar nome da key pair para .bashrc
      lineinfile:
        path: ~/.bashrc
        line: "export EC2_KEY_NAME={{ ec2_key_name }}"
        create: yes

    - name: Criar grupo de segurança
      amazon.aws.ec2_group:
        name: "master-ansible-sg"
        description: "Security group for master-ansible"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports:
              - 80
            cidr_ip: 0.0.0.0/0
        state: present
        region: "{{ region }}"
      register: sg

    - name: Renderizar o user_data com a chave pública
      set_fact:
        user_data: "{{ user_data_template | replace('AWS_ACCESS_KEY_ID_PLACEHOLDER', lookup('env', 'AWS_ACCESS_KEY_ID')) | replace('AWS_SECRET_ACCESS_KEY_PLACEHOLDER', lookup('env', 'AWS_SECRET_ACCESS_KEY')) }}"

    - name: Lançar instância EC2
      amazon.aws.ec2_instance:
        name: "master-ansible"
        key_name: "{{ ec2_key_name }}"
        instance_type: "{{ ec2_instance_type }}"
        image_id: "{{ ec2_image }}"
        wait: yes
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: "{{ ec2_volume_size }}"
        network:
          assign_public_ip: yes
        security_groups: ["master-ansible-sg"]
        user_data: "{{ user_data }}"
        region: "{{ region }}"
      register: ec2

    - name: Depurar detalhes da instância EC2
      debug:
        var: ec2

    - name: Variáveis de ambiente carregadas com sucesso!
      debug:
        msg: "Variáveis de ambiente carregadas com sucesso!"
