---
- name: Criar Application Load Balancer
  hosts: localhost
  gather_facts: no
  collections:
    - community.aws
    - amazon.aws
  vars_files:
    - vpc_vars.yml
    - scaling_group_vars.yml
  tasks:
    - name: Exibir variáveis carregadas de vpc_vars.yml
      debug:
        msg: "SG_ID: {{ sg_id }}, SUBNET_ID_AZ1: {{ subnet_id_az1 }}, SUBNET_ID_AZ2: {{ subnet_id_az2 }}, VPC_ID: {{ vpc_id }}"

    - name: Exibir variáveis carregadas de scaling_group_vars.yml
      debug:
        msg: "ASG_NAME: {{ asg_name }}"

    - name: Verificar se as variáveis estão definidas
      fail:
        msg: "As variáveis sg_id, subnet_id_az1, subnet_id_az2, asg_name, region ou vpc_id estão vazias!"
      when: sg_id == "" or subnet_id_az1 == "" or subnet_id_az2 == "" or asg_name == "" or region == "" or vpc_id == ""

    - name: Criar Target Group
      community.aws.elb_target_group:
        name: "webserver-tg"
        protocol: HTTP
        port: 80
        vpc_id: "{{ vpc_id }}"
        health_check_protocol: HTTP
        health_check_port: traffic-port
        health_check_path: /
        health_check_interval_seconds: 30
        health_check_timeout_seconds: 5
        healthy_threshold_count: 2
        unhealthy_threshold_count: 2
        target_type: instance
        region: "{{ region }}"
        state: present
      register: target_group

    - name: Criar Load Balancer
      community.aws.elb_application_lb:
        name: "webserver-alb"
        state: present
        security_groups: [ "{{ sg_id }}" ]
        subnets: [ "{{ subnet_id_az1 }}", "{{ subnet_id_az2 }}" ]
        scheme: internet-facing
        listeners:
          - Protocol: HTTP
            Port: 80
            DefaultActions:
              - Type: forward
                TargetGroupArn: "{{ target_group.target_group_arn }}"
        region: "{{ region }}"
      register: alb

    - name: Associar Target Group ao Auto Scaling Group
      community.aws.autoscaling_group:
        name: "{{ asg_name }}"
        target_group_arns: [ "{{ target_group.target_group_arn }}" ]
        region: "{{ region }}"
        state: present

    - name: Exibir detalhes do Load Balancer
      debug:
        var: alb

    - name: Exportar variáveis de Load Balancer para alb_vars.yml
      copy:
        content: |
          alb_dns_name: "{{ alb.dns_name }}"
        dest: "alb_vars.yml"
