---
- name: Criar VPC e Subnets na AWS
  hosts: localhost
  gather_facts: no
  vars:
    region: us-east-1
    vpc_cidr: "10.0.0.0/16"
    subnet_cidr_az1: "10.0.1.0/24"
    subnet_cidr_az2: "10.0.2.0/24"
  tasks:
    - name: Remover variáveis existentes do .bashrc
      lineinfile:
        path: ~/.bashrc
        state: absent
        regexp: '^export VPC_ID=|^export SUBNET_ID_AZ1=|^export SUBNET_ID_AZ2=|^export SUBNET_CIDR_AZ1=|^export SUBNET_CIDR_AZ2='

    - name: Criar VPC
      amazon.aws.ec2_vpc_net:
        name: minha_vpc
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ region }}"
        state: present
      register: vpc

    - name: Criar Subnet na primeira AZ
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ subnet_cidr_az1 }}"
        region: "{{ region }}"
        state: present
        map_public: yes
        az: "us-east-1a"
      register: subnet_az1

    - name: Criar Subnet na segunda AZ
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ subnet_cidr_az2 }}"
        region: "{{ region }}"
        state: present
        map_public: yes
        az: "us-east-1b"
      register: subnet_az2

    - name: Criar Internet Gateway
      amazon.aws.ec2_vpc_igw:
        region: "{{ region }}"
        state: present
      register: igw

    - name: Anexar Internet Gateway à VPC
      amazon.aws.ec2_vpc_igw:
        region: "{{ region }}"
        vpc_id: "{{ vpc.vpc.id }}"
        internet_gateway_id: "{{ igw.gateway_id }}"
        state: present
      when: igw.gateway_id is defined

    - name: Criar e configurar a tabela de roteamento
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        state: present
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
          - dest: "{{ vpc_cidr }}"
            local_target: true
        subnets:
          - "{{ subnet_az1.subnet.id }}"
          - "{{ subnet_az2.subnet.id }}"
      register: route_table

    - name: Exportar variáveis para .bashrc
      lineinfile:
        path: ~/.bashrc
        create: yes
        line: |
          export VPC_ID={{ vpc.vpc.id }}
          export SUBNET_ID_AZ1={{ subnet_az1.subnet.id }}
          export SUBNET_ID_AZ2={{ subnet_az2.subnet.id }}
          export SUBNET_CIDR_AZ1={{ subnet_cidr_az1 }}
          export SUBNET_CIDR_AZ2={{ subnet_cidr_az2 }}

    - name: Carregar novas variáveis de ambiente do .bashrc
      shell: /bin/bash -c "source ~/.bashrc && env"
      register: new_shell_output

    - name: Variáveis de ambiente carregadas com sucesso!
      debug:
        msg: "VPC_ID: {{ new_shell_output.stdout_lines | select('search', '^VPC_ID=') | list | first | split('=') | last }}, SUBNET_ID_AZ1: {{ new_shell_output.stdout_lines | select('search', '^SUBNET_ID_AZ1=') | list | first | split('=') | last }}, SUBNET_ID_AZ2: {{ new_shell_output.stdout_lines | select('search', '^SUBNET_ID_AZ2=') | list | first | split('=') | last }}, SUBNET_CIDR_AZ1: {{ new_shell_output.stdout_lines | select('search', '^SUBNET_CIDR_AZ1=') | list | first | split('=') | last }}, SUBNET_CIDR_AZ2: {{ new_shell_output.stdout_lines | select('search', '^SUBNET_CIDR_AZ2=') | list | first | split('=') | last }}"
