---
- name: Criar VPC e Subnets na AWS
  hosts: localhost
  gather_facts: no
  vars:
    region: us-east-1
    vpc_cidr: "10.0.0.0/16"
    subnet_cidr_az1: "10.0.1.0/24"
    subnet_cidr_az2: "10.0.2.0/24"
    vpc_vars_file: "vars/vpc_vars.yml"
  tasks:
    - name: Criar VPC
      amazon.aws.ec2_vpc_net:
        name: minha_vpc
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ region }}"
        state: present
      register: vpc

    - name: Criar Subnet na primeira AZ
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ subnet_cidr_az1 }}"
        region: "{{ region }}"
        state: present
        map_public: yes
        az: "us-east-1a"
      register: subnet_az1

    - name: Criar Subnet na segunda AZ
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ subnet_cidr_az2 }}"
        region: "{{ region }}"
        state: present
        map_public: yes
        az: "us-east-1b"
      register: subnet_az2

    - name: Criar Internet Gateway
      amazon.aws.ec2_vpc_igw:
        region: "{{ region }}"
        state: present
      register: igw

    - name: Anexar Internet Gateway à VPC
      amazon.aws.ec2_vpc_igw:
        region: "{{ region }}"
        vpc_id: "{{ vpc.vpc.id }}"
        internet_gateway_id: "{{ igw.gateway_id }}"
        state: present
      when: igw.gateway_id is defined

    - name: Criar e configurar a tabela de roteamento
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        state: present
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
          - dest: "{{ vpc_cidr }}"
            local_target: true
        subnets:
          - "{{ subnet_az1.subnet.id }}"
          - "{{ subnet_az2.subnet.id }}"
      register: route_table

    - name: Exportar variáveis para o arquivo de variáveis do Ansible
      copy:
        content: |
          vpc_id: "{{ vpc.vpc.id }}"
          subnet_id_az1: "{{ subnet_az1.subnet.id }}"
          subnet_id_az2: "{{ subnet_az2.subnet.id }}"
          subnet_cidr_az1: "{{ subnet_cidr_az1 }}"
          subnet_cidr_az2: "{{ subnet_cidr_az2 }}"
          region: "{{ region }}"
        dest: "{{ vpc_vars_file }}"

    - name: Variáveis exportadas com sucesso!
      debug:
        msg: "VPC_ID: {{ vpc.vpc.id }}, SUBNET_ID_AZ1: {{ subnet_az1.subnet.id }}, SUBNET_ID_AZ2: {{ subnet_az2.subnet.id }}, SUBNET_CIDR_AZ1: {{ subnet_cidr_az1 }}, SUBNET_CIDR_AZ2: {{ subnet_cidr_az2 }}"
