---
- name: Criar Launch Template a partir da AMI
  hosts: localhost
  gather_facts: no
  collections:
    - community.aws
  vars_files:
    - ec2_vars.yml
    - ami_vars.yml
  tasks:
    - name: Exibir variáveis carregadas de ec2_vars.yml
      debug:
        msg: "EC2_KEY_NAME: {{ ec2_key_name }}, SG_ID: {{ sg_id }}"

    - name: Exibir variáveis carregadas de ami_vars.yml
      debug:
        msg: "AMI_ID: {{ ami_id }}"

    - name: Verificar se as variáveis estão definidas
      fail:
        msg: "As variáveis ami_id, ec2_key_name ou sg_id não foram encontradas!"
      when: ami_id is not defined or ec2_key_name is not defined or sg_id is not defined

    - name: Setar variáveis de ambiente
      set_fact:
        region: "{{ lookup('ini', 'AWS_DEFAULT_REGION section=default file=~/.aws/credentials') }}"

    - name: Criar Launch Template
      community.aws.ec2_launch_template:
        name: "webserver-launch-template"
        version_description: "Initial version"
        image_id: "{{ ami_id }}"
        instance_type: "t2.micro"
        key_name: "{{ ec2_key_name }}"
        security_group_ids: [ "{{ sg_id }}" ]
        block_device_mappings:
          - device_name: "/dev/sda1"
            ebs:
              volume_size: 10
              delete_on_termination: true
        state: present
        region: "{{ region }}"
      register: launch_template_result

    - name: Exibir detalhes do Launch Template criado
      debug:
        var: launch_template_result

    - name: Exportar Launch Template variáveis para launch_template_vars.yml
      copy:
        content: |
          launch_template_id: "{{ launch_template_result.default_template.launch_template_id }}"
          launch_template_name: "{{ launch_template_result.default_template.launch_template_name }}"
          launch_template_version: "{{ launch_template_result.default_template.version_number }}"
        dest: "launch_template_vars.yml"

    - name: Carregar novas variáveis de launch_template_vars.yml
      include_vars:
        file: "launch_template_vars.yml"

    - name: Variáveis de Launch Template carregadas com sucesso!
      debug:
        msg: "LAUNCH_TEMPLATE_ID: {{ launch_template_id }}, LAUNCH_TEMPLATE_NAME: {{ launch_template_name }}, LAUNCH_TEMPLATE_VERSION: {{ launch_template_version }}"
